basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
]

learning_users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

from basic_app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^basic_app/',include('basic_app.urls')),
    path('admin/', admin.site.urls),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^special/',views.special,name='special'),
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User  # Cand folosesc useri adaug asta
# Create your models here.


class UserProfileInfo(models.Model):
    """User profile info."""

    user = models.OneToOneField(User, on_delete=models.PROTECT)

    # Additional
    portofolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portofolio_site','profile_pic')

basic_app/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse

from .forms import UserForm, UserProfileInfoForm


def index(request):
    """Landing page.

    :param request:
    :return:
    """
    return render(request, 'basic_app/index.html')


@login_required
def user_logout(request):
    """Log out user.

    :param request:
    :return:
    """
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def special(request):
    return HttpResponse("You are logged in, nice!")


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user  # aici setez relatia 1 la 1

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not active")
        else:
            print("Someone tried to login adn failed!")
            print("Username: {} adn password {}".format(username, password))
            return HttpResponse("invalid login details supplied")
    else:
        return render(request, 'basic_app/login.html', {})

templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">Django home</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>

          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'basic_app:user_login' %}">Login</a></li>
          {% endif %}
        </ul>

      </div>
    </nav>

    {% block body_block %}


    {% endblock %}
  </body>
</html>

templates/basic_app/index.html
{% extends "basic_app/base.html"%}

{% block body_block %}

<div class="jumbotron">
  <h1>Django level five</h1>
</div>

{% endblock  %}

templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>Please log in</h1>
  <form action="{% url 'basic_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username</label>
    <input type="text" name="username" placeholder="ENter username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">

  </form>
</div>

{% endblock %}

templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}

{% load staticfiles %}  #ca sa bag statice de alea nebune

{% block body_block %}

<div class="jumbotron">
  {% if registered %}
    <h1>Thank you for registering!</h1>
  {% else %}
    <h1>Register here!</h1>
    <h3>Fill out the form:</h3>

    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ user_form.as_p}}
      {{ profile_form.as_p}}
      <input type="submit" name="" value="Register">
    </form>
  {% endif %}
</div>

{% endblock %}